# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 180460c4fa2e7bd0fc25d662664d57af2ffc7f9e6f12be65c37210bad8c67d728a1fa6dd0aff3084316883122e87a862cbb20af657929506645440d09c1d3989

test:
  secret_key_base: 3405cbfdecda40e34de13cf4ebb69bba11b3b963df8698c37b305546e547e94f31d31889a1e84bbcf87b6a1917af5e8bad0ba55c38b774bc6a8045aaabc2fb35

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
